### ISSUE TITLE
Feature request: CMYK support

### ISSUE THREAD

**Issue by tilman-schieber** [FirefoxGraphics/qcms#35]
Currently qcms does not support CMYK input or output profiles.
 see https://bugzilla.mozilla.org/show_bug.cgi?id=1474560
 
I am not sure if this feature is disabled because LUT-based profiles are not supported at all or if just the CMYK to PCS and the PCS to CMYK conversion function is missing.

While CMYK is not common in a browser context, previewing for-print graphics that use CMYK colors is certainly a use case that will become more common with desktop applications moving to webassembly.
Specifically the need arose in [this](https://github.com/typst/typst/issues/3143) application.

**Comment by jrmuizel** [comment]
Support for CMYK was added in https://github.com/FirefoxGraphics/qcms/commit/7f4e64c718ff493cbaeef9b15b2526b9f4c568e7

**Comment by tilman-schieber** [comment]
Ah okay, so the issue [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1474560) is just a problem with the C bindings. Because that's still open.

I'll close this, thanks for the quick reply

**Comment by jrmuizel** [comment]
An example of how to use it is here: https://github.com/FirefoxGraphics/qcms/blob/2fb1aa3d85cc807013495dfd28f8829f92892a37/src/gtest.rs#L935

I'll publish a new version of the crate as soon https://phabricator.services.mozilla.com/D197955 makes its way over here.
